# Generated by Django 6.0.3 on 2026-03-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userprofile_photo_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='background',
            new_name='background_image',
        ),
    ]
